///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace viethouse.MODULE.DangKy.KiemTraButtonDangKy_TroVe
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The NhapThieuFieldBatBuoc recording.
    /// </summary>
    [TestModule("a4caac1f-8c38-48eb-9cf7-6bf75222356e", ModuleType.Recording, 1)]
    public partial class NhapThieuFieldBatBuoc : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::viethouse.viethouseRepository repository.
        /// </summary>
        public static global::viethouse.viethouseRepository repo = global::viethouse.viethouseRepository.Instance;

        static NhapThieuFieldBatBuoc instance = new NhapThieuFieldBatBuoc();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public NhapThieuFieldBatBuoc()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static NhapThieuFieldBatBuoc Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ThongTinTaiKhoản.ĐăngKy' at 18;16.", repo.ThongTinTaiKhoản.ĐăngKyInfo, new RecordItemIndex(0));
            repo.ThongTinTaiKhoản.ĐăngKy.Click("18;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ThongTinTaiKhoản.ĐăngKy1' at 226;23.", repo.ThongTinTaiKhoản.ĐăngKy1Info, new RecordItemIndex(1));
            repo.ThongTinTaiKhoản.ĐăngKy1.Click("226;23");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ThongTinTaiKhoản.FullNameError'.", repo.ThongTinTaiKhoản.FullNameErrorInfo, new RecordItemIndex(2));
            Validate.Exists(repo.ThongTinTaiKhoản.FullNameErrorInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ThongTinTaiKhoản.EmailAddressError'.", repo.ThongTinTaiKhoản.EmailAddressErrorInfo, new RecordItemIndex(3));
            Validate.Exists(repo.ThongTinTaiKhoản.EmailAddressErrorInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ThongTinTaiKhoản.PhoneNumberError'.", repo.ThongTinTaiKhoản.PhoneNumberErrorInfo, new RecordItemIndex(4));
            Validate.Exists(repo.ThongTinTaiKhoản.PhoneNumberErrorInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ThongTinTaiKhoản.RegModalPasswordError'.", repo.ThongTinTaiKhoản.RegModalPasswordErrorInfo, new RecordItemIndex(5));
            Validate.Exists(repo.ThongTinTaiKhoản.RegModalPasswordErrorInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ThongTinTaiKhoản.AcceptedError'.", repo.ThongTinTaiKhoản.AcceptedErrorInfo, new RecordItemIndex(6));
            Validate.Exists(repo.ThongTinTaiKhoản.AcceptedErrorInfo);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
