///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace viethouse.MODULE.DangKy.MatKhauTextbox
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The KhongNhapMatKhau recording.
    /// </summary>
    [TestModule("ff41e5aa-f985-4558-9383-ceeddd21b9cf", ModuleType.Recording, 1)]
    public partial class KhongNhapMatKhau : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::viethouse.viethouseRepository repository.
        /// </summary>
        public static global::viethouse.viethouseRepository repo = global::viethouse.viethouseRepository.Instance;

        static KhongNhapMatKhau instance = new KhongNhapMatKhau();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public KhongNhapMatKhau()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static KhongNhapMatKhau Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ThongTinTaiKhoản.ĐăngKy' at 34;16.", repo.ThongTinTaiKhoản.ĐăngKyInfo, new RecordItemIndex(0));
            repo.ThongTinTaiKhoản.ĐăngKy.Click("34;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ThongTinTaiKhoản.FullName' at 130;27.", repo.ThongTinTaiKhoản.FullNameInfo, new RecordItemIndex(1));
            repo.ThongTinTaiKhoản.FullName.Click("130;27");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Tran Gia Luong' with focus on 'ThongTinTaiKhoản.FullName'.", repo.ThongTinTaiKhoản.FullNameInfo, new RecordItemIndex(2));
            repo.ThongTinTaiKhoản.FullName.PressKeys("Tran Gia Luong");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'ThongTinTaiKhoản.FullName'.", repo.ThongTinTaiKhoản.FullNameInfo, new RecordItemIndex(3));
            repo.ThongTinTaiKhoản.FullName.PressKeys("{Tab}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'abc{LShiftKey down}@{LShiftKey up}gmail.com{Tab}0123456789'.", new RecordItemIndex(4));
            Keyboard.Press("abc{LShiftKey down}@{LShiftKey up}gmail.com{Tab}0123456789");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ThongTinTaiKhoản.Checkmark' at 11;10.", repo.ThongTinTaiKhoản.CheckmarkInfo, new RecordItemIndex(5));
            repo.ThongTinTaiKhoản.Checkmark.Click("11;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ThongTinTaiKhoản.ĐăngKy1' at 214;25.", repo.ThongTinTaiKhoản.ĐăngKy1Info, new RecordItemIndex(6));
            repo.ThongTinTaiKhoản.ĐăngKy1.Click("214;25");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ThongTinTaiKhoản.RegModalPasswordError'.", repo.ThongTinTaiKhoản.RegModalPasswordErrorInfo, new RecordItemIndex(7));
            Validate.Exists(repo.ThongTinTaiKhoản.RegModalPasswordErrorInfo);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
