///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace viethouse.MODULE.DangKy.MatKhauTextbox
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The MatKhauNhHon3KyTu recording.
    /// </summary>
    [TestModule("6eb4f96d-e3ac-43a5-a963-9de88e042271", ModuleType.Recording, 1)]
    public partial class MatKhauNhHon3KyTu : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::viethouse.viethouseRepository repository.
        /// </summary>
        public static global::viethouse.viethouseRepository repo = global::viethouse.viethouseRepository.Instance;

        static MatKhauNhHon3KyTu instance = new MatKhauNhHon3KyTu();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public MatKhauNhHon3KyTu()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static MatKhauNhHon3KyTu Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ThongTinTaiKhoản.ĐăngKy' at 39;22.", repo.ThongTinTaiKhoản.ĐăngKyInfo, new RecordItemIndex(0));
            repo.ThongTinTaiKhoản.ĐăngKy.Click("39;22");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ThongTinTaiKhoản.FullName' at 157;27.", repo.ThongTinTaiKhoản.FullNameInfo, new RecordItemIndex(1));
            repo.ThongTinTaiKhoản.FullName.Click("157;27");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'gialuong' with focus on 'ThongTinTaiKhoản.FullName'.", repo.ThongTinTaiKhoản.FullNameInfo, new RecordItemIndex(2));
            repo.ThongTinTaiKhoản.FullName.PressKeys("gialuong");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'ThongTinTaiKhoản.FullName'.", repo.ThongTinTaiKhoản.FullNameInfo, new RecordItemIndex(3));
            repo.ThongTinTaiKhoản.FullName.PressKeys("{Tab}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'abc{LShiftKey down}@{LShiftKey up}gmail.com{Tab}'.", new RecordItemIndex(4));
            Keyboard.Press("abc{LShiftKey down}@{LShiftKey up}gmail.com{Tab}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '099'.", new RecordItemIndex(5));
            Keyboard.Press("099");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '8'.", new RecordItemIndex(6));
            Keyboard.Press("8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '998998{Tab}12{Capital}12{Back}{Back}{Tab}12'.", new RecordItemIndex(7));
            Keyboard.Press("998998{Tab}12{Capital}12{Back}{Back}{Tab}12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ThongTinTaiKhoản.Checkmark' at 9;15.", repo.ThongTinTaiKhoản.CheckmarkInfo, new RecordItemIndex(8));
            repo.ThongTinTaiKhoản.Checkmark.Click("9;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ThongTinTaiKhoản.ĐăngKy1' at 200;20.", repo.ThongTinTaiKhoản.ĐăngKy1Info, new RecordItemIndex(9));
            repo.ThongTinTaiKhoản.ĐăngKy1.Click("200;20");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ThongTinTaiKhoản.MậtKhẩuPhảiCoItNhất3KyTự'.", repo.ThongTinTaiKhoản.MậtKhẩuPhảiCoItNhất3KyTựInfo, new RecordItemIndex(10));
            Validate.Exists(repo.ThongTinTaiKhoản.MậtKhẩuPhảiCoItNhất3KyTựInfo);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
