///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace viethouse.MODULE.DangKy
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The khonghoten recording.
    /// </summary>
    [TestModule("2814fff6-e9f3-443a-9cde-cc066e385143", ModuleType.Recording, 1)]
    public partial class khonghoten : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::viethouse.viethouseRepository repository.
        /// </summary>
        public static global::viethouse.viethouseRepository repo = global::viethouse.viethouseRepository.Instance;

        static khonghoten instance = new khonghoten();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public khonghoten()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static khonghoten Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ThongTinTaiKhoản1.ĐăngKy' at 30;22.", repo.ThongTinTaiKhoản1.ĐăngKyInfo, new RecordItemIndex(0));
            repo.ThongTinTaiKhoản1.ĐăngKy.Click("30;22");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ThongTinTaiKhoản1.EmailAddress' at 128;11.", repo.ThongTinTaiKhoản1.EmailAddressInfo, new RecordItemIndex(1));
            repo.ThongTinTaiKhoản1.EmailAddress.Click("128;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'abc{LShiftKey down}#{LShiftKey up}{Back}{LShiftKey down}@{LShiftKey up}gmail.com{Tab}0123456789{Tab}1234{Tab}1234' with focus on 'ThongTinTaiKhoản1.EmailAddress'.", repo.ThongTinTaiKhoản1.EmailAddressInfo, new RecordItemIndex(2));
            repo.ThongTinTaiKhoản1.EmailAddress.PressKeys("abc{LShiftKey down}#{LShiftKey up}{Back}{LShiftKey down}@{LShiftKey up}gmail.com{Tab}0123456789{Tab}1234{Tab}1234");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ThongTinTaiKhoản1.Checkmark' at 16;5.", repo.ThongTinTaiKhoản1.CheckmarkInfo, new RecordItemIndex(3));
            repo.ThongTinTaiKhoản1.Checkmark.Click("16;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ThongTinTaiKhoản1.ĐăngKy1' at 243;21.", repo.ThongTinTaiKhoản1.ĐăngKy1Info, new RecordItemIndex(4));
            repo.ThongTinTaiKhoản1.ĐăngKy1.Click("243;21");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ThongTinTaiKhoản1.FullNameError'.", repo.ThongTinTaiKhoản1.FullNameErrorInfo, new RecordItemIndex(5));
            Validate.Exists(repo.ThongTinTaiKhoản1.FullNameErrorInfo);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
