///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace viethouse
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the viethouseRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    [RepositoryFolder("be12804b-861a-458d-8a69-b5351599e914")]
    public partial class viethouseRepository : RepoGenBaseFolder
    {
        static viethouseRepository instance = new viethouseRepository();
        viethouseRepositoryFolders.ThongTinTaiKhoảnGoogleChromeAppFolder _thongtintaikhoảngooglechrome;
        viethouseRepositoryFolders.ThongTinTaiKhoảnAppFolder _thongtintaikhoản;
        viethouseRepositoryFolders.TimKiemAppFolder _timkiem;

        /// <summary>
        /// Gets the singleton class instance representing the viethouseRepository element repository.
        /// </summary>
        [RepositoryFolder("be12804b-861a-458d-8a69-b5351599e914")]
        public static viethouseRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public viethouseRepository() 
            : base("viethouseRepository", "/", null, 0, false, "be12804b-861a-458d-8a69-b5351599e914", ".\\RepositoryImages\\viethouseRepositorybe12804b.rximgres")
        {
            _thongtintaikhoảngooglechrome = new viethouseRepositoryFolders.ThongTinTaiKhoảnGoogleChromeAppFolder(this);
            _thongtintaikhoản = new viethouseRepositoryFolders.ThongTinTaiKhoảnAppFolder(this);
            _timkiem = new viethouseRepositoryFolders.TimKiemAppFolder(this);
        }

#region Variables

        string _radSoilType = "1";

        /// <summary>
        /// Gets or sets the value of variable radSoilType.
        /// </summary>
        [TestVariable("602fb70c-ba46-4faa-99aa-8f51edb897cb")]
        public string radSoilType
        {
            get { return _radSoilType; }
            set { _radSoilType = value; }
        }

        string _itemSoilType = "11";

        /// <summary>
        /// Gets or sets the value of variable itemSoilType.
        /// </summary>
        [TestVariable("95119461-757d-4f9e-a9a6-38b051d9100d")]
        public string itemSoilType
        {
            get { return _itemSoilType; }
            set { _itemSoilType = value; }
        }

        string _notification = "Mua bán nhà đất - Bất động sản House Viet T12/2021";

        /// <summary>
        /// Gets or sets the value of variable notification.
        /// </summary>
        [TestVariable("9eb3c8dc-39c6-4356-8c96-07c0ff50d78d")]
        public string notification
        {
            get { return _notification; }
            set { _notification = value; }
        }

        string _element = "Mua bán nhà đất - Bất động sản House Viet T12/2021";

        /// <summary>
        /// Gets or sets the value of variable element.
        /// </summary>
        [TestVariable("86bf0f96-bb1e-43e6-b947-1c34c4472a50")]
        public string element
        {
            get { return _element; }
            set { _element = value; }
        }

        string _itemCity = "1";

        /// <summary>
        /// Gets or sets the value of variable itemCity.
        /// </summary>
        [TestVariable("a4fb7f91-26fd-4024-a1f0-990f2ca9b84e")]
        public string itemCity
        {
            get { return _itemCity; }
            set { _itemCity = value; }
        }

        string _itemPrice = "1";

        /// <summary>
        /// Gets or sets the value of variable itemPrice.
        /// </summary>
        [TestVariable("71f1d338-e7eb-49f6-8185-f2fca633bb94")]
        public string itemPrice
        {
            get { return _itemPrice; }
            set { _itemPrice = value; }
        }

        string _itemArea = "1";

        /// <summary>
        /// Gets or sets the value of variable itemArea.
        /// </summary>
        [TestVariable("2b3fa6de-2378-4320-9585-8cde98cf4a5c")]
        public string itemArea
        {
            get { return _itemArea; }
            set { _itemArea = value; }
        }

        string _validateList = "Đường 30/4, Thủ Dầu Một, Bình Dương";

        /// <summary>
        /// Gets or sets the value of variable validateList.
        /// </summary>
        [TestVariable("3839a5a7-e5dc-447c-9c4e-6833f66de8af")]
        public string validateList
        {
            get { return _validateList; }
            set { _validateList = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("be12804b-861a-458d-8a69-b5351599e914")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ThongTinTaiKhoảnGoogleChrome folder.
        /// </summary>
        [RepositoryFolder("c1343daf-a299-458b-bdda-33e79c0ccca0")]
        public virtual viethouseRepositoryFolders.ThongTinTaiKhoảnGoogleChromeAppFolder ThongTinTaiKhoảnGoogleChrome
        {
            get { return _thongtintaikhoảngooglechrome; }
        }

        /// <summary>
        /// The ThongTinTaiKhoản folder.
        /// </summary>
        [RepositoryFolder("8bf2f4f1-7755-434a-81c1-0200264cb700")]
        public virtual viethouseRepositoryFolders.ThongTinTaiKhoảnAppFolder ThongTinTaiKhoản
        {
            get { return _thongtintaikhoản; }
        }

        /// <summary>
        /// The TimKiem folder.
        /// </summary>
        [RepositoryFolder("94d5d368-05fa-47a1-8524-10fd8f7ebbf9")]
        public virtual viethouseRepositoryFolders.TimKiemAppFolder TimKiem
        {
            get { return _timkiem; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    public partial class viethouseRepositoryFolders
    {
        /// <summary>
        /// The ThongTinTaiKhoảnGoogleChromeAppFolder folder.
        /// </summary>
        [RepositoryFolder("c1343daf-a299-458b-bdda-33e79c0ccca0")]
        public partial class ThongTinTaiKhoảnGoogleChromeAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _đongInfo;

            /// <summary>
            /// Creates a new ThongTinTaiKhoảnGoogleChrome  folder.
            /// </summary>
            public ThongTinTaiKhoảnGoogleChromeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ThongTinTaiKhoảnGoogleChrome", "/form[@title~'^Thông\\ tin\\ tài\\ khoản\\ -\\ Goo']", parentFolder, 30000, null, true, "c1343daf-a299-458b-bdda-33e79c0ccca0", "")
            {
                _đongInfo = new RepoItemInfo(this, "Đong", "container[@accessiblename~'^Thông\\ tin\\ tài\\ khoản\\ -\\ Goo']/container[@accessiblename='Google Chrome']/container/container[2]/container[1]//tabpage[@accessiblename='Thông tin tài khoản']/button[@accessiblename='Đóng']", 30000, null, "dc1c907d-f01e-429e-b2f0-f4444f2c97c1");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c1343daf-a299-458b-bdda-33e79c0ccca0")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c1343daf-a299-458b-bdda-33e79c0ccca0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Đong item.
            /// </summary>
            [RepositoryItem("dc1c907d-f01e-429e-b2f0-f4444f2c97c1")]
            public virtual Ranorex.Button Đong
            {
                get
                {
                    return _đongInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Đong item info.
            /// </summary>
            [RepositoryItemInfo("dc1c907d-f01e-429e-b2f0-f4444f2c97c1")]
            public virtual RepoItemInfo ĐongInfo
            {
                get
                {
                    return _đongInfo;
                }
            }
        }

        /// <summary>
        /// The ThongTinTaiKhoảnAppFolder folder.
        /// </summary>
        [RepositoryFolder("8bf2f4f1-7755-434a-81c1-0200264cb700")]
        public partial class ThongTinTaiKhoảnAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _profilefullnameInfo;
            RepoItemInfo _changeinfoInfo;
            RepoItemInfo _profilefullnameerrorInfo;

            /// <summary>
            /// Creates a new ThongTinTaiKhoản  folder.
            /// </summary>
            public ThongTinTaiKhoảnAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ThongTinTaiKhoản", "/dom[3]", parentFolder, 30000, null, false, "8bf2f4f1-7755-434a-81c1-0200264cb700", "")
            {
                _profilefullnameInfo = new RepoItemInfo(this, "ProfileFullName", ".//input[#'Profile_FullName']", 30000, null, "4d0b8010-45b2-4001-b55b-dc13b5f68645");
                _changeinfoInfo = new RepoItemInfo(this, "ChangeInfo", ".//button[#'ChangeInfo']", 30000, null, "d602ef3e-313f-42e7-b07d-5b4d1351e7e8");
                _profilefullnameerrorInfo = new RepoItemInfo(this, "ProfileFullNameError", ".//span[#'Profile_FullName-error']", 30000, null, "e599b393-1e58-45a7-988d-c6730563db34");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8bf2f4f1-7755-434a-81c1-0200264cb700")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8bf2f4f1-7755-434a-81c1-0200264cb700")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ProfileFullName item.
            /// </summary>
            [RepositoryItem("4d0b8010-45b2-4001-b55b-dc13b5f68645")]
            public virtual Ranorex.InputTag ProfileFullName
            {
                get
                {
                    return _profilefullnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The ProfileFullName item info.
            /// </summary>
            [RepositoryItemInfo("4d0b8010-45b2-4001-b55b-dc13b5f68645")]
            public virtual RepoItemInfo ProfileFullNameInfo
            {
                get
                {
                    return _profilefullnameInfo;
                }
            }

            /// <summary>
            /// The ChangeInfo item.
            /// </summary>
            [RepositoryItem("d602ef3e-313f-42e7-b07d-5b4d1351e7e8")]
            public virtual Ranorex.ButtonTag ChangeInfo
            {
                get
                {
                    return _changeinfoInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ChangeInfo item info.
            /// </summary>
            [RepositoryItemInfo("d602ef3e-313f-42e7-b07d-5b4d1351e7e8")]
            public virtual RepoItemInfo ChangeInfoInfo
            {
                get
                {
                    return _changeinfoInfo;
                }
            }

            /// <summary>
            /// The ProfileFullNameError item.
            /// </summary>
            [RepositoryItem("e599b393-1e58-45a7-988d-c6730563db34")]
            public virtual Ranorex.SpanTag ProfileFullNameError
            {
                get
                {
                    return _profilefullnameerrorInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The ProfileFullNameError item info.
            /// </summary>
            [RepositoryItemInfo("e599b393-1e58-45a7-988d-c6730563db34")]
            public virtual RepoItemInfo ProfileFullNameErrorInfo
            {
                get
                {
                    return _profilefullnameerrorInfo;
                }
            }
        }

        /// <summary>
        /// The TimKiemAppFolder folder.
        /// </summary>
        [RepositoryFolder("94d5d368-05fa-47a1-8524-10fd8f7ebbf9")]
        public partial class TimKiemAppFolder : RepoGenBaseFolder
        {
            viethouseRepositoryFolders.ValidateListSearchFolder _validatelistsearch;
            RepoItemInfo _txtkeywordsInfo;
            RepoItemInfo _btnsearchInfo;
            RepoItemInfo _spinsoiltypeInfo;
            RepoItemInfo _itemsoiltypeInfo;
            RepoItemInfo _spincityInfo;
            RepoItemInfo _itemcityInfo;
            RepoItemInfo _spinpriceInfo;
            RepoItemInfo _itempriceInfo;
            RepoItemInfo _spinareaInfo;
            RepoItemInfo _itemareaInfo;
            RepoItemInfo _mainnavInfo;
            RepoItemInfo _validatesoiltypeInfo;
            RepoItemInfo _validatesearchInfo;
            RepoItemInfo _validatetypeInfo;

            /// <summary>
            /// Creates a new TimKiem  folder.
            /// </summary>
            public TimKiemAppFolder(RepoGenBaseFolder parentFolder) :
                    base("TimKiem", "/dom[@domain='houseviet.vn']", parentFolder, 30000, null, false, "94d5d368-05fa-47a1-8524-10fd8f7ebbf9", "")
            {
                _validatelistsearch = new viethouseRepositoryFolders.ValidateListSearchFolder(this);
                _txtkeywordsInfo = new RepoItemInfo(this, "txtKeywords", ".//input[#'txtKeywords']", 30000, null, "ef67cfd5-a66f-4d90-bf87-ff41f2546dde");
                _btnsearchInfo = new RepoItemInfo(this, "btnsearch", ".//tag[#'main']/section[1]/?/?/form[@name='search-form']//button[@innertext=' Tìm kiếm ']", 30000, null, "2d50b3d3-7763-4842-ae93-bc5cba0d806f");
                _spinsoiltypeInfo = new RepoItemInfo(this, "spinSoilType", ".//div[#'Cate']/div", 30000, null, "83de2626-e5e1-4dbb-9bff-803426dfe85b");
                _itemsoiltypeInfo = new RepoItemInfo(this, "itemSoilType", ".//div[#'Cate']/div[2]/div[2]/div[1]/div/label[$itemSoilType]", 30000, null, "84d6473e-87e7-456b-a746-02c562718122");
                _spincityInfo = new RepoItemInfo(this, "spinCity", ".//div[#'City']/div", 30000, null, "86286acd-e504-40b7-b84e-b73db9320791");
                _itemcityInfo = new RepoItemInfo(this, "itemCity", ".//div[#'City']/div[2]/div[2]/div[1]/div/label[$itemCity]", 30000, null, "843f7ee8-314f-490e-8607-dfe794f9a272");
                _spinpriceInfo = new RepoItemInfo(this, "spinPrice", ".//div[#'Price']/div", 30000, null, "5bb57517-5790-48f1-ad68-23b890585b9c");
                _itempriceInfo = new RepoItemInfo(this, "itemPrice", ".//div[#'Price']/div[2]/div/div[1]/div/label[$itemPrice]", 30000, null, "b2b94204-e065-4f09-8ea8-7308ab89bb54");
                _spinareaInfo = new RepoItemInfo(this, "spinArea", ".//div[#'Area']/div", 30000, null, "c17f0fc0-a6ce-4bd3-87ed-5c6e1be22449");
                _itemareaInfo = new RepoItemInfo(this, "itemArea", ".//div[#'Area']/div[2]/div/div[1]/div/label[$itemArea]", 30000, null, "d8a23012-93b5-407b-abae-f14651a0586d");
                _mainnavInfo = new RepoItemInfo(this, "MainNav", ".//div[#'main-nav']", 30000, null, "a37d7a8e-a373-49bb-b2f0-c5e8247a942b");
                _validatesoiltypeInfo = new RepoItemInfo(this, "validateSoilType", ".//tag[#'main']/article//div[@innertext~'^Bạn\\ đang\\ xem\\ 15\\ tin\\ rao\\ t']/a[@innertext=$element]", 30000, null, "f8dbb079-3d76-4475-b0be-255bec3f0392");
                _validatesearchInfo = new RepoItemInfo(this, "validateSearch", ".//tag[#'main']/article/div/div/div[1]/div[1]/div[@innertext~'^Bạn\\ đan']", 30000, null, "b6f0b7b5-8930-45df-8291-ec36b831ea01");
                _validatetypeInfo = new RepoItemInfo(this, "validateType", ".//tag[#'main']/article/div/div/div[1]/div[1]/div[@innertext~'^Bạn\\ đan']", 30000, null, "da5dbc3c-6a42-4635-ae46-2cafebe521d1");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("94d5d368-05fa-47a1-8524-10fd8f7ebbf9")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("94d5d368-05fa-47a1-8524-10fd8f7ebbf9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The txtKeywords item.
            /// </summary>
            [RepositoryItem("ef67cfd5-a66f-4d90-bf87-ff41f2546dde")]
            public virtual Ranorex.InputTag txtKeywords
            {
                get
                {
                    return _txtkeywordsInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The txtKeywords item info.
            /// </summary>
            [RepositoryItemInfo("ef67cfd5-a66f-4d90-bf87-ff41f2546dde")]
            public virtual RepoItemInfo txtKeywordsInfo
            {
                get
                {
                    return _txtkeywordsInfo;
                }
            }

            /// <summary>
            /// The btnsearch item.
            /// </summary>
            [RepositoryItem("2d50b3d3-7763-4842-ae93-bc5cba0d806f")]
            public virtual Ranorex.ButtonTag btnsearch
            {
                get
                {
                    return _btnsearchInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The btnsearch item info.
            /// </summary>
            [RepositoryItemInfo("2d50b3d3-7763-4842-ae93-bc5cba0d806f")]
            public virtual RepoItemInfo btnsearchInfo
            {
                get
                {
                    return _btnsearchInfo;
                }
            }

            /// <summary>
            /// The spinSoilType item.
            /// </summary>
            [RepositoryItem("83de2626-e5e1-4dbb-9bff-803426dfe85b")]
            public virtual Ranorex.DivTag spinSoilType
            {
                get
                {
                    return _spinsoiltypeInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The spinSoilType item info.
            /// </summary>
            [RepositoryItemInfo("83de2626-e5e1-4dbb-9bff-803426dfe85b")]
            public virtual RepoItemInfo spinSoilTypeInfo
            {
                get
                {
                    return _spinsoiltypeInfo;
                }
            }

            /// <summary>
            /// The itemSoilType item.
            /// </summary>
            [RepositoryItem("84d6473e-87e7-456b-a746-02c562718122")]
            public virtual Ranorex.LabelTag itemSoilType
            {
                get
                {
                    return _itemsoiltypeInfo.CreateAdapter<Ranorex.LabelTag>(true);
                }
            }

            /// <summary>
            /// The itemSoilType item info.
            /// </summary>
            [RepositoryItemInfo("84d6473e-87e7-456b-a746-02c562718122")]
            public virtual RepoItemInfo itemSoilTypeInfo
            {
                get
                {
                    return _itemsoiltypeInfo;
                }
            }

            /// <summary>
            /// The spinCity item.
            /// </summary>
            [RepositoryItem("86286acd-e504-40b7-b84e-b73db9320791")]
            public virtual Ranorex.DivTag spinCity
            {
                get
                {
                    return _spincityInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The spinCity item info.
            /// </summary>
            [RepositoryItemInfo("86286acd-e504-40b7-b84e-b73db9320791")]
            public virtual RepoItemInfo spinCityInfo
            {
                get
                {
                    return _spincityInfo;
                }
            }

            /// <summary>
            /// The itemCity item.
            /// </summary>
            [RepositoryItem("843f7ee8-314f-490e-8607-dfe794f9a272")]
            public virtual Ranorex.LabelTag itemCity
            {
                get
                {
                    return _itemcityInfo.CreateAdapter<Ranorex.LabelTag>(true);
                }
            }

            /// <summary>
            /// The itemCity item info.
            /// </summary>
            [RepositoryItemInfo("843f7ee8-314f-490e-8607-dfe794f9a272")]
            public virtual RepoItemInfo itemCityInfo
            {
                get
                {
                    return _itemcityInfo;
                }
            }

            /// <summary>
            /// The spinPrice item.
            /// </summary>
            [RepositoryItem("5bb57517-5790-48f1-ad68-23b890585b9c")]
            public virtual Ranorex.DivTag spinPrice
            {
                get
                {
                    return _spinpriceInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The spinPrice item info.
            /// </summary>
            [RepositoryItemInfo("5bb57517-5790-48f1-ad68-23b890585b9c")]
            public virtual RepoItemInfo spinPriceInfo
            {
                get
                {
                    return _spinpriceInfo;
                }
            }

            /// <summary>
            /// The itemPrice item.
            /// </summary>
            [RepositoryItem("b2b94204-e065-4f09-8ea8-7308ab89bb54")]
            public virtual Ranorex.LabelTag itemPrice
            {
                get
                {
                    return _itempriceInfo.CreateAdapter<Ranorex.LabelTag>(true);
                }
            }

            /// <summary>
            /// The itemPrice item info.
            /// </summary>
            [RepositoryItemInfo("b2b94204-e065-4f09-8ea8-7308ab89bb54")]
            public virtual RepoItemInfo itemPriceInfo
            {
                get
                {
                    return _itempriceInfo;
                }
            }

            /// <summary>
            /// The spinArea item.
            /// </summary>
            [RepositoryItem("c17f0fc0-a6ce-4bd3-87ed-5c6e1be22449")]
            public virtual Ranorex.DivTag spinArea
            {
                get
                {
                    return _spinareaInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The spinArea item info.
            /// </summary>
            [RepositoryItemInfo("c17f0fc0-a6ce-4bd3-87ed-5c6e1be22449")]
            public virtual RepoItemInfo spinAreaInfo
            {
                get
                {
                    return _spinareaInfo;
                }
            }

            /// <summary>
            /// The itemArea item.
            /// </summary>
            [RepositoryItem("d8a23012-93b5-407b-abae-f14651a0586d")]
            public virtual Ranorex.LabelTag itemArea
            {
                get
                {
                    return _itemareaInfo.CreateAdapter<Ranorex.LabelTag>(true);
                }
            }

            /// <summary>
            /// The itemArea item info.
            /// </summary>
            [RepositoryItemInfo("d8a23012-93b5-407b-abae-f14651a0586d")]
            public virtual RepoItemInfo itemAreaInfo
            {
                get
                {
                    return _itemareaInfo;
                }
            }

            /// <summary>
            /// The MainNav item.
            /// </summary>
            [RepositoryItem("a37d7a8e-a373-49bb-b2f0-c5e8247a942b")]
            public virtual Ranorex.DivTag MainNav
            {
                get
                {
                    return _mainnavInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The MainNav item info.
            /// </summary>
            [RepositoryItemInfo("a37d7a8e-a373-49bb-b2f0-c5e8247a942b")]
            public virtual RepoItemInfo MainNavInfo
            {
                get
                {
                    return _mainnavInfo;
                }
            }

            /// <summary>
            /// The validateSoilType item.
            /// </summary>
            [RepositoryItem("f8dbb079-3d76-4475-b0be-255bec3f0392")]
            public virtual Ranorex.ATag validateSoilType
            {
                get
                {
                    return _validatesoiltypeInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The validateSoilType item info.
            /// </summary>
            [RepositoryItemInfo("f8dbb079-3d76-4475-b0be-255bec3f0392")]
            public virtual RepoItemInfo validateSoilTypeInfo
            {
                get
                {
                    return _validatesoiltypeInfo;
                }
            }

            /// <summary>
            /// The validateSearch item.
            /// </summary>
            [RepositoryItem("b6f0b7b5-8930-45df-8291-ec36b831ea01")]
            public virtual Ranorex.DivTag validateSearch
            {
                get
                {
                    return _validatesearchInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The validateSearch item info.
            /// </summary>
            [RepositoryItemInfo("b6f0b7b5-8930-45df-8291-ec36b831ea01")]
            public virtual RepoItemInfo validateSearchInfo
            {
                get
                {
                    return _validatesearchInfo;
                }
            }

            /// <summary>
            /// The validateType item.
            /// </summary>
            [RepositoryItem("da5dbc3c-6a42-4635-ae46-2cafebe521d1")]
            public virtual Ranorex.DivTag validateType
            {
                get
                {
                    return _validatetypeInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The validateType item info.
            /// </summary>
            [RepositoryItemInfo("da5dbc3c-6a42-4635-ae46-2cafebe521d1")]
            public virtual RepoItemInfo validateTypeInfo
            {
                get
                {
                    return _validatetypeInfo;
                }
            }

            /// <summary>
            /// The validateListSearch folder.
            /// </summary>
            [RepositoryFolder("af4a5c36-9e5d-4c41-b7eb-10413d92a65a")]
            public virtual viethouseRepositoryFolders.ValidateListSearchFolder validateListSearch
            {
                get { return _validatelistsearch; }
            }
        }

        /// <summary>
        /// The ValidateListSearchFolder folder.
        /// </summary>
        [RepositoryFolder("af4a5c36-9e5d-4c41-b7eb-10413d92a65a")]
        public partial class ValidateListSearchFolder : RepoGenBaseFolder
        {
            RepoItemInfo _validatelist1Info;
            RepoItemInfo _validatelist2Info;
            RepoItemInfo _validatelist3Info;
            RepoItemInfo _validatelist4Info;
            RepoItemInfo _validatelist5Info;

            /// <summary>
            /// Creates a new validateListSearch  folder.
            /// </summary>
            public ValidateListSearchFolder(RepoGenBaseFolder parentFolder) :
                    base("validateListSearch", ".//tag[#'main']/section[1]/div[2]/form[@name='search-form']//ul", parentFolder, 30000, null, false, "af4a5c36-9e5d-4c41-b7eb-10413d92a65a", "")
            {
                _validatelist1Info = new RepoItemInfo(this, "validateList1", "li[2]/span[@innertext~$validateList]", 30000, null, "f1ccad8e-d24a-4b45-8402-f56147c1509d");
                _validatelist2Info = new RepoItemInfo(this, "validateList2", "li[3]/span[@innertext~$validateList]", 30000, null, "0cb632c9-9e0a-4934-9e7d-4b0abef8a2f3");
                _validatelist3Info = new RepoItemInfo(this, "validateList3", "li[4]/span[@innertext~$validateList]", 30000, null, "4b5fb9e6-a979-46c2-863f-7fcb8b687eb9");
                _validatelist4Info = new RepoItemInfo(this, "validateList4", "li[5]/span[@innertext~$validateList]", 30000, null, "3d426cf6-89f8-4c52-8d7c-49f7c70e5bde");
                _validatelist5Info = new RepoItemInfo(this, "validateList5", "li[6]/span[@innertext~$validateList]", 30000, null, "667c33bd-b983-4e28-b5e2-8da57b21f2da");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("af4a5c36-9e5d-4c41-b7eb-10413d92a65a")]
            public virtual Ranorex.UlTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.UlTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("af4a5c36-9e5d-4c41-b7eb-10413d92a65a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The validateList1 item.
            /// </summary>
            [RepositoryItem("f1ccad8e-d24a-4b45-8402-f56147c1509d")]
            public virtual Ranorex.SpanTag validateList1
            {
                get
                {
                    return _validatelist1Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The validateList1 item info.
            /// </summary>
            [RepositoryItemInfo("f1ccad8e-d24a-4b45-8402-f56147c1509d")]
            public virtual RepoItemInfo validateList1Info
            {
                get
                {
                    return _validatelist1Info;
                }
            }

            /// <summary>
            /// The validateList2 item.
            /// </summary>
            [RepositoryItem("0cb632c9-9e0a-4934-9e7d-4b0abef8a2f3")]
            public virtual Ranorex.SpanTag validateList2
            {
                get
                {
                    return _validatelist2Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The validateList2 item info.
            /// </summary>
            [RepositoryItemInfo("0cb632c9-9e0a-4934-9e7d-4b0abef8a2f3")]
            public virtual RepoItemInfo validateList2Info
            {
                get
                {
                    return _validatelist2Info;
                }
            }

            /// <summary>
            /// The validateList3 item.
            /// </summary>
            [RepositoryItem("4b5fb9e6-a979-46c2-863f-7fcb8b687eb9")]
            public virtual Ranorex.SpanTag validateList3
            {
                get
                {
                    return _validatelist3Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The validateList3 item info.
            /// </summary>
            [RepositoryItemInfo("4b5fb9e6-a979-46c2-863f-7fcb8b687eb9")]
            public virtual RepoItemInfo validateList3Info
            {
                get
                {
                    return _validatelist3Info;
                }
            }

            /// <summary>
            /// The validateList4 item.
            /// </summary>
            [RepositoryItem("3d426cf6-89f8-4c52-8d7c-49f7c70e5bde")]
            public virtual Ranorex.SpanTag validateList4
            {
                get
                {
                    return _validatelist4Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The validateList4 item info.
            /// </summary>
            [RepositoryItemInfo("3d426cf6-89f8-4c52-8d7c-49f7c70e5bde")]
            public virtual RepoItemInfo validateList4Info
            {
                get
                {
                    return _validatelist4Info;
                }
            }

            /// <summary>
            /// The validateList5 item.
            /// </summary>
            [RepositoryItem("667c33bd-b983-4e28-b5e2-8da57b21f2da")]
            public virtual Ranorex.SpanTag validateList5
            {
                get
                {
                    return _validatelist5Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The validateList5 item info.
            /// </summary>
            [RepositoryItemInfo("667c33bd-b983-4e28-b5e2-8da57b21f2da")]
            public virtual RepoItemInfo validateList5Info
            {
                get
                {
                    return _validatelist5Info;
                }
            }
        }

    }
#pragma warning restore 0436
}