///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace viethouse
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the viethouseRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    [RepositoryFolder("be12804b-861a-458d-8a69-b5351599e914")]
    public partial class viethouseRepository : RepoGenBaseFolder
    {
        static viethouseRepository instance = new viethouseRepository();
        viethouseRepositoryFolders.ThongTinTaiKhoảnGoogleChromeAppFolder _thongtintaikhoảngooglechrome;
        viethouseRepositoryFolders.ThongTinTaiKhoảnAppFolder _thongtintaikhoản;
        viethouseRepositoryFolders.TimKiemAppFolder _timkiem;

        /// <summary>
        /// Gets the singleton class instance representing the viethouseRepository element repository.
        /// </summary>
        [RepositoryFolder("be12804b-861a-458d-8a69-b5351599e914")]
        public static viethouseRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public viethouseRepository() 
            : base("viethouseRepository", "/", null, 0, false, "be12804b-861a-458d-8a69-b5351599e914", ".\\RepositoryImages\\viethouseRepositorybe12804b.rximgres")
        {
            _thongtintaikhoảngooglechrome = new viethouseRepositoryFolders.ThongTinTaiKhoảnGoogleChromeAppFolder(this);
            _thongtintaikhoản = new viethouseRepositoryFolders.ThongTinTaiKhoảnAppFolder(this);
            _timkiem = new viethouseRepositoryFolders.TimKiemAppFolder(this);
        }

#region Variables

        string _radSoilType = "1";

        /// <summary>
        /// Gets or sets the value of variable radSoilType.
        /// </summary>
        [TestVariable("602fb70c-ba46-4faa-99aa-8f51edb897cb")]
        public string radSoilType
        {
            get { return _radSoilType; }
            set { _radSoilType = value; }
        }

        string _itemSoilType = "11";

        /// <summary>
        /// Gets or sets the value of variable itemSoilType.
        /// </summary>
        [TestVariable("95119461-757d-4f9e-a9a6-38b051d9100d")]
        public string itemSoilType
        {
            get { return _itemSoilType; }
            set { _itemSoilType = value; }
        }

        string _notification = "Mua bán nhà đất - Bất động sản House Viet T12/2021";

        /// <summary>
        /// Gets or sets the value of variable notification.
        /// </summary>
        [TestVariable("9eb3c8dc-39c6-4356-8c96-07c0ff50d78d")]
        public string notification
        {
            get { return _notification; }
            set { _notification = value; }
        }

        string _element = "Mua bán nhà đất - Bất động sản House Viet T12/2021";

        /// <summary>
        /// Gets or sets the value of variable element.
        /// </summary>
        [TestVariable("86bf0f96-bb1e-43e6-b947-1c34c4472a50")]
        public string element
        {
            get { return _element; }
            set { _element = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("be12804b-861a-458d-8a69-b5351599e914")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ThongTinTaiKhoảnGoogleChrome folder.
        /// </summary>
        [RepositoryFolder("c1343daf-a299-458b-bdda-33e79c0ccca0")]
        public virtual viethouseRepositoryFolders.ThongTinTaiKhoảnGoogleChromeAppFolder ThongTinTaiKhoảnGoogleChrome
        {
            get { return _thongtintaikhoảngooglechrome; }
        }

        /// <summary>
        /// The ThongTinTaiKhoản folder.
        /// </summary>
        [RepositoryFolder("8bf2f4f1-7755-434a-81c1-0200264cb700")]
        public virtual viethouseRepositoryFolders.ThongTinTaiKhoảnAppFolder ThongTinTaiKhoản
        {
            get { return _thongtintaikhoản; }
        }

        /// <summary>
        /// The TimKiem folder.
        /// </summary>
        [RepositoryFolder("94d5d368-05fa-47a1-8524-10fd8f7ebbf9")]
        public virtual viethouseRepositoryFolders.TimKiemAppFolder TimKiem
        {
            get { return _timkiem; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    public partial class viethouseRepositoryFolders
    {
        /// <summary>
        /// The ThongTinTaiKhoảnGoogleChromeAppFolder folder.
        /// </summary>
        [RepositoryFolder("c1343daf-a299-458b-bdda-33e79c0ccca0")]
        public partial class ThongTinTaiKhoảnGoogleChromeAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _đongInfo;

            /// <summary>
            /// Creates a new ThongTinTaiKhoảnGoogleChrome  folder.
            /// </summary>
            public ThongTinTaiKhoảnGoogleChromeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ThongTinTaiKhoảnGoogleChrome", "/form[@title~'^Thông\\ tin\\ tài\\ khoản\\ -\\ Goo']", parentFolder, 30000, null, true, "c1343daf-a299-458b-bdda-33e79c0ccca0", "")
            {
                _đongInfo = new RepoItemInfo(this, "Đong", "container[@accessiblename~'^Thông\\ tin\\ tài\\ khoản\\ -\\ Goo']/container[@accessiblename='Google Chrome']/container/container[2]/container[1]//tabpage[@accessiblename='Thông tin tài khoản']/button[@accessiblename='Đóng']", 30000, null, "dc1c907d-f01e-429e-b2f0-f4444f2c97c1");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c1343daf-a299-458b-bdda-33e79c0ccca0")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c1343daf-a299-458b-bdda-33e79c0ccca0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Đong item.
            /// </summary>
            [RepositoryItem("dc1c907d-f01e-429e-b2f0-f4444f2c97c1")]
            public virtual Ranorex.Button Đong
            {
                get
                {
                    return _đongInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Đong item info.
            /// </summary>
            [RepositoryItemInfo("dc1c907d-f01e-429e-b2f0-f4444f2c97c1")]
            public virtual RepoItemInfo ĐongInfo
            {
                get
                {
                    return _đongInfo;
                }
            }
        }

        /// <summary>
        /// The ThongTinTaiKhoảnAppFolder folder.
        /// </summary>
        [RepositoryFolder("8bf2f4f1-7755-434a-81c1-0200264cb700")]
        public partial class ThongTinTaiKhoảnAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _profilefullnameInfo;
            RepoItemInfo _changeinfoInfo;
            RepoItemInfo _profilefullnameerrorInfo;

            /// <summary>
            /// Creates a new ThongTinTaiKhoản  folder.
            /// </summary>
            public ThongTinTaiKhoảnAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ThongTinTaiKhoản", "/dom[3]", parentFolder, 30000, null, false, "8bf2f4f1-7755-434a-81c1-0200264cb700", "")
            {
                _profilefullnameInfo = new RepoItemInfo(this, "ProfileFullName", ".//input[#'Profile_FullName']", 30000, null, "4d0b8010-45b2-4001-b55b-dc13b5f68645");
                _changeinfoInfo = new RepoItemInfo(this, "ChangeInfo", ".//button[#'ChangeInfo']", 30000, null, "d602ef3e-313f-42e7-b07d-5b4d1351e7e8");
                _profilefullnameerrorInfo = new RepoItemInfo(this, "ProfileFullNameError", ".//span[#'Profile_FullName-error']", 30000, null, "e599b393-1e58-45a7-988d-c6730563db34");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8bf2f4f1-7755-434a-81c1-0200264cb700")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8bf2f4f1-7755-434a-81c1-0200264cb700")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ProfileFullName item.
            /// </summary>
            [RepositoryItem("4d0b8010-45b2-4001-b55b-dc13b5f68645")]
            public virtual Ranorex.InputTag ProfileFullName
            {
                get
                {
                    return _profilefullnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The ProfileFullName item info.
            /// </summary>
            [RepositoryItemInfo("4d0b8010-45b2-4001-b55b-dc13b5f68645")]
            public virtual RepoItemInfo ProfileFullNameInfo
            {
                get
                {
                    return _profilefullnameInfo;
                }
            }

            /// <summary>
            /// The ChangeInfo item.
            /// </summary>
            [RepositoryItem("d602ef3e-313f-42e7-b07d-5b4d1351e7e8")]
            public virtual Ranorex.ButtonTag ChangeInfo
            {
                get
                {
                    return _changeinfoInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ChangeInfo item info.
            /// </summary>
            [RepositoryItemInfo("d602ef3e-313f-42e7-b07d-5b4d1351e7e8")]
            public virtual RepoItemInfo ChangeInfoInfo
            {
                get
                {
                    return _changeinfoInfo;
                }
            }

            /// <summary>
            /// The ProfileFullNameError item.
            /// </summary>
            [RepositoryItem("e599b393-1e58-45a7-988d-c6730563db34")]
            public virtual Ranorex.SpanTag ProfileFullNameError
            {
                get
                {
                    return _profilefullnameerrorInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The ProfileFullNameError item info.
            /// </summary>
            [RepositoryItemInfo("e599b393-1e58-45a7-988d-c6730563db34")]
            public virtual RepoItemInfo ProfileFullNameErrorInfo
            {
                get
                {
                    return _profilefullnameerrorInfo;
                }
            }
        }

        /// <summary>
        /// The TimKiemAppFolder folder.
        /// </summary>
        [RepositoryFolder("94d5d368-05fa-47a1-8524-10fd8f7ebbf9")]
        public partial class TimKiemAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _txtkeywordsInfo;
            RepoItemInfo _btnsearchInfo;
            RepoItemInfo _spinsoiltypeInfo;
            RepoItemInfo _itemsoiltypeInfo;
            RepoItemInfo _mainnavInfo;
            RepoItemInfo _validatesoiltypeInfo;

            /// <summary>
            /// Creates a new TimKiem  folder.
            /// </summary>
            public TimKiemAppFolder(RepoGenBaseFolder parentFolder) :
                    base("TimKiem", "/dom[@domain='houseviet.vn']", parentFolder, 30000, null, false, "94d5d368-05fa-47a1-8524-10fd8f7ebbf9", "")
            {
                _txtkeywordsInfo = new RepoItemInfo(this, "txtKeywords", ".//input[#'txtKeywords']", 30000, null, "ef67cfd5-a66f-4d90-bf87-ff41f2546dde");
                _btnsearchInfo = new RepoItemInfo(this, "btnsearch", ".//tag[#'main']/section[1]/?/?/form[@name='search-form']//button[@innertext=' Tìm kiếm ']", 30000, null, "2d50b3d3-7763-4842-ae93-bc5cba0d806f");
                _spinsoiltypeInfo = new RepoItemInfo(this, "spinSoilType", ".//div[#'Cate']/div", 30000, null, "83de2626-e5e1-4dbb-9bff-803426dfe85b");
                _itemsoiltypeInfo = new RepoItemInfo(this, "itemSoilType", ".//div[#'Cate']/div[2]/div[2]/div[1]/div/label[$itemSoilType]", 30000, null, "84d6473e-87e7-456b-a746-02c562718122");
                _mainnavInfo = new RepoItemInfo(this, "MainNav", ".//div[#'main-nav']", 30000, null, "a37d7a8e-a373-49bb-b2f0-c5e8247a942b");
                _validatesoiltypeInfo = new RepoItemInfo(this, "validateSoilType", ".//tag[#'main']/article//div[@innertext~'Bạn đang xem 15 tin rao trong tổng số 104.201 tin ']/a[@innertext=$element]", 30000, null, "f8dbb079-3d76-4475-b0be-255bec3f0392");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("94d5d368-05fa-47a1-8524-10fd8f7ebbf9")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("94d5d368-05fa-47a1-8524-10fd8f7ebbf9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The txtKeywords item.
            /// </summary>
            [RepositoryItem("ef67cfd5-a66f-4d90-bf87-ff41f2546dde")]
            public virtual Ranorex.InputTag txtKeywords
            {
                get
                {
                    return _txtkeywordsInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The txtKeywords item info.
            /// </summary>
            [RepositoryItemInfo("ef67cfd5-a66f-4d90-bf87-ff41f2546dde")]
            public virtual RepoItemInfo txtKeywordsInfo
            {
                get
                {
                    return _txtkeywordsInfo;
                }
            }

            /// <summary>
            /// The btnsearch item.
            /// </summary>
            [RepositoryItem("2d50b3d3-7763-4842-ae93-bc5cba0d806f")]
            public virtual Ranorex.ButtonTag btnsearch
            {
                get
                {
                    return _btnsearchInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The btnsearch item info.
            /// </summary>
            [RepositoryItemInfo("2d50b3d3-7763-4842-ae93-bc5cba0d806f")]
            public virtual RepoItemInfo btnsearchInfo
            {
                get
                {
                    return _btnsearchInfo;
                }
            }

            /// <summary>
            /// The spinSoilType item.
            /// </summary>
            [RepositoryItem("83de2626-e5e1-4dbb-9bff-803426dfe85b")]
            public virtual Ranorex.DivTag spinSoilType
            {
                get
                {
                    return _spinsoiltypeInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The spinSoilType item info.
            /// </summary>
            [RepositoryItemInfo("83de2626-e5e1-4dbb-9bff-803426dfe85b")]
            public virtual RepoItemInfo spinSoilTypeInfo
            {
                get
                {
                    return _spinsoiltypeInfo;
                }
            }

            /// <summary>
            /// The itemSoilType item.
            /// </summary>
            [RepositoryItem("84d6473e-87e7-456b-a746-02c562718122")]
            public virtual Ranorex.LabelTag itemSoilType
            {
                get
                {
                    return _itemsoiltypeInfo.CreateAdapter<Ranorex.LabelTag>(true);
                }
            }

            /// <summary>
            /// The itemSoilType item info.
            /// </summary>
            [RepositoryItemInfo("84d6473e-87e7-456b-a746-02c562718122")]
            public virtual RepoItemInfo itemSoilTypeInfo
            {
                get
                {
                    return _itemsoiltypeInfo;
                }
            }

            /// <summary>
            /// The MainNav item.
            /// </summary>
            [RepositoryItem("a37d7a8e-a373-49bb-b2f0-c5e8247a942b")]
            public virtual Ranorex.DivTag MainNav
            {
                get
                {
                    return _mainnavInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The MainNav item info.
            /// </summary>
            [RepositoryItemInfo("a37d7a8e-a373-49bb-b2f0-c5e8247a942b")]
            public virtual RepoItemInfo MainNavInfo
            {
                get
                {
                    return _mainnavInfo;
                }
            }

            /// <summary>
            /// The validateSoilType item.
            /// </summary>
            [RepositoryItem("f8dbb079-3d76-4475-b0be-255bec3f0392")]
            public virtual Ranorex.ATag validateSoilType
            {
                get
                {
                    return _validatesoiltypeInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The validateSoilType item info.
            /// </summary>
            [RepositoryItemInfo("f8dbb079-3d76-4475-b0be-255bec3f0392")]
            public virtual RepoItemInfo validateSoilTypeInfo
            {
                get
                {
                    return _validatesoiltypeInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}