///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace viethouse.MODULE.CapNhatThongTin.CMT
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CMT8KyTuSo recording.
    /// </summary>
    [TestModule("f04e989a-b9a9-43fa-997b-2b8e23dfd5bf", ModuleType.Recording, 1)]
    public partial class CMT8KyTuSo : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::viethouse.viethouseRepository repository.
        /// </summary>
        public static global::viethouse.viethouseRepository repo = global::viethouse.viethouseRepository.Instance;

        static CMT8KyTuSo instance = new CMT8KyTuSo();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CMT8KyTuSo()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CMT8KyTuSo Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ThongTinTaiKhoản2.ProfileIdentityNo' at 145;25.", repo.ThongTinTaiKhoản2.ProfileIdentityNoInfo, new RecordItemIndex(0));
            repo.ThongTinTaiKhoản2.ProfileIdentityNo.Click("145;25");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Akey}{LControlKey up}{Back}03520000{Return}' with focus on 'ThongTinTaiKhoản2.ProfileIdentityNo'.", repo.ThongTinTaiKhoản2.ProfileIdentityNoInfo, new RecordItemIndex(1));
            repo.ThongTinTaiKhoản2.ProfileIdentityNo.PressKeys("{Akey}{LControlKey up}{Back}03520000{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating NotExists on item 'ThongTinTaiKhoản2.CậpNhậtThongTinTaiKhoảnThanhCong'.", repo.ThongTinTaiKhoản2.CậpNhậtThongTinTaiKhoảnThanhCongInfo, new RecordItemIndex(2));
            Validate.NotExists(repo.ThongTinTaiKhoản2.CậpNhậtThongTinTaiKhoảnThanhCongInfo);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
