///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace viethouse.MODULE.CapNhatThongTin.GioiTinh
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Nam recording.
    /// </summary>
    [TestModule("6e602d3e-5da1-4f3d-9a10-ca0ef108d571", ModuleType.Recording, 1)]
    public partial class Nam : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::viethouse.viethouseRepository repository.
        /// </summary>
        public static global::viethouse.viethouseRepository repo = global::viethouse.viethouseRepository.Instance;

        static Nam instance = new Nam();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Nam()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Nam Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ThongTinTaiKhoản2.Checkmark' at 19;14.", repo.ThongTinTaiKhoản2.CheckmarkInfo, new RecordItemIndex(0));
            repo.ThongTinTaiKhoản2.Checkmark.Click("19;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ThongTinTaiKhoản2.ChangeInfo' at 131;33.", repo.ThongTinTaiKhoản2.ChangeInfoInfo, new RecordItemIndex(1));
            repo.ThongTinTaiKhoản2.ChangeInfo.Click("131;33");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ThongTinTaiKhoảnGoogleChrome.TảiLại' at 15;14.", repo.ThongTinTaiKhoảnGoogleChrome.TảiLạiInfo, new RecordItemIndex(2));
            repo.ThongTinTaiKhoảnGoogleChrome.TảiLại.Click("15;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ThongTinTaiKhoản2.LabelTagNam'.", repo.ThongTinTaiKhoản2.LabelTagNamInfo, new RecordItemIndex(3));
            Validate.Exists(repo.ThongTinTaiKhoản2.LabelTagNamInfo);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
