///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace viethouse.MODULE.CapNhatThongTin.DiaChi
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The PhuongXaSai recording.
    /// </summary>
    [TestModule("76d8899a-7543-4a8a-b959-7d3d13c6a54e", ModuleType.Recording, 1)]
    public partial class PhuongXaSai : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::viethouse.viethouseRepository repository.
        /// </summary>
        public static global::viethouse.viethouseRepository repo = global::viethouse.viethouseRepository.Instance;

        static PhuongXaSai instance = new PhuongXaSai();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public PhuongXaSai()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static PhuongXaSai Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ThongTinTaiKhoản2.XoaTấtCảCacMụcĐaChọn' at 19;14.", repo.ThongTinTaiKhoản2.XoaTấtCảCacMụcĐaChọnInfo, new RecordItemIndex(0));
            repo.ThongTinTaiKhoản2.XoaTấtCảCacMụcĐaChọn.Click("19;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ThongTinTaiKhoản2.Search' at 130;22.", repo.ThongTinTaiKhoản2.SearchInfo, new RecordItemIndex(1));
            repo.ThongTinTaiKhoản2.Search.Click("130;22");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Down}{Return}' with focus on 'ThongTinTaiKhoản2.Search'.", repo.ThongTinTaiKhoản2.SearchInfo, new RecordItemIndex(2));
            repo.ThongTinTaiKhoản2.Search.PressKeys("{Down}{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ThongTinTaiKhoản2.Select2DistrictIdContainer' at 222;15.", repo.ThongTinTaiKhoản2.Select2DistrictIdContainerInfo, new RecordItemIndex(3));
            repo.ThongTinTaiKhoản2.Select2DistrictIdContainer.Click("222;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ThongTinTaiKhoản2.Search' at 137;24.", repo.ThongTinTaiKhoản2.SearchInfo, new RecordItemIndex(4));
            repo.ThongTinTaiKhoản2.Search.Click("137;24");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Hoang{Tab}' with focus on 'ThongTinTaiKhoản2.Search'.", repo.ThongTinTaiKhoản2.SearchInfo, new RecordItemIndex(5));
            repo.ThongTinTaiKhoản2.Search.PressKeys("Hoang{Tab}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ThongTinTaiKhoản2.PhườngXa' at 142;8.", repo.ThongTinTaiKhoản2.PhườngXaInfo, new RecordItemIndex(6));
            repo.ThongTinTaiKhoản2.PhườngXa.Click("142;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ThongTinTaiKhoản2.Search' at 110;18.", repo.ThongTinTaiKhoản2.SearchInfo, new RecordItemIndex(7));
            repo.ThongTinTaiKhoản2.Search.Click("110;18");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'abc' with focus on 'ThongTinTaiKhoản2.Search'.", repo.ThongTinTaiKhoản2.SearchInfo, new RecordItemIndex(8));
            repo.ThongTinTaiKhoản2.Search.PressKeys("abc");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ThongTinTaiKhoản2.Copy_of_KhongTimThấyKếtQuả'.", repo.ThongTinTaiKhoản2.Copy_of_KhongTimThấyKếtQuảInfo, new RecordItemIndex(9));
            Validate.Exists(repo.ThongTinTaiKhoản2.Copy_of_KhongTimThấyKếtQuảInfo);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
