///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace viethouse.MODULE.CapNhatThongTin.DiaChi
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The PhuongXa recording.
    /// </summary>
    [TestModule("7e011c5d-0d12-4468-a9c4-f413836b8079", ModuleType.Recording, 1)]
    public partial class PhuongXa : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::viethouse.viethouseRepository repository.
        /// </summary>
        public static global::viethouse.viethouseRepository repo = global::viethouse.viethouseRepository.Instance;

        static PhuongXa instance = new PhuongXa();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public PhuongXa()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static PhuongXa Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ThongTinTaiKhoản2.XoaTấtCảCacMụcĐaChọn' at 20;16.", repo.ThongTinTaiKhoản2.XoaTấtCảCacMụcĐaChọnInfo, new RecordItemIndex(0));
            repo.ThongTinTaiKhoản2.XoaTấtCảCacMụcĐaChọn.Click("20;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ThongTinTaiKhoản2.Search' at 141;17.", repo.ThongTinTaiKhoản2.SearchInfo, new RecordItemIndex(1));
            repo.ThongTinTaiKhoản2.Search.Click("141;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Down}' with focus on 'ThongTinTaiKhoản2.Search'.", repo.ThongTinTaiKhoản2.SearchInfo, new RecordItemIndex(2));
            repo.ThongTinTaiKhoản2.Search.PressKeys("{Down}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'ThongTinTaiKhoản2.Search'.", repo.ThongTinTaiKhoản2.SearchInfo, new RecordItemIndex(3));
            repo.ThongTinTaiKhoản2.Search.PressKeys("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ThongTinTaiKhoản2.Select2DistrictIdContainer' at 178;8.", repo.ThongTinTaiKhoản2.Select2DistrictIdContainerInfo, new RecordItemIndex(4));
            repo.ThongTinTaiKhoản2.Select2DistrictIdContainer.Click("178;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ThongTinTaiKhoản2.Search' at 136;22.", repo.ThongTinTaiKhoản2.SearchInfo, new RecordItemIndex(5));
            repo.ThongTinTaiKhoản2.Search.Click("136;22");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Hoang' with focus on 'ThongTinTaiKhoản2.Search'.", repo.ThongTinTaiKhoản2.SearchInfo, new RecordItemIndex(6));
            repo.ThongTinTaiKhoản2.Search.PressKeys("Hoang");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'ThongTinTaiKhoản2.Search'.", repo.ThongTinTaiKhoản2.SearchInfo, new RecordItemIndex(7));
            repo.ThongTinTaiKhoản2.Search.PressKeys("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ThongTinTaiKhoản2.PhườngXa' at 88;0.", repo.ThongTinTaiKhoản2.PhườngXaInfo, new RecordItemIndex(8));
            repo.ThongTinTaiKhoản2.PhườngXa.Click("88;0");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ThongTinTaiKhoản2.Search' at 88;25.", repo.ThongTinTaiKhoản2.SearchInfo, new RecordItemIndex(9));
            repo.ThongTinTaiKhoản2.Search.Click("88;25");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Hoang' with focus on 'ThongTinTaiKhoản2.Search'.", repo.ThongTinTaiKhoản2.SearchInfo, new RecordItemIndex(10));
            repo.ThongTinTaiKhoản2.Search.PressKeys("Hoang");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence ' Liet{Return}' with focus on 'ThongTinTaiKhoản2.Search'.", repo.ThongTinTaiKhoản2.SearchInfo, new RecordItemIndex(11));
            repo.ThongTinTaiKhoản2.Search.PressKeys(" Liet{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ThongTinTaiKhoản2.ChangeInfo' at 164;24.", repo.ThongTinTaiKhoản2.ChangeInfoInfo, new RecordItemIndex(12));
            repo.ThongTinTaiKhoản2.ChangeInfo.Click("164;24");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ThongTinTaiKhoản2.CậpNhậtThongTinTaiKhoảnThanhCong1'.", repo.ThongTinTaiKhoản2.CậpNhậtThongTinTaiKhoảnThanhCong1Info, new RecordItemIndex(13));
            Validate.Exists(repo.ThongTinTaiKhoản2.CậpNhậtThongTinTaiKhoảnThanhCong1Info);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
