///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace viethouse.MODULE.CapNhatThongTin.DiaChi
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The QuanHuyenSai recording.
    /// </summary>
    [TestModule("fe9df41b-75e6-4dad-80dd-bbace2447d77", ModuleType.Recording, 1)]
    public partial class QuanHuyenSai : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::viethouse.viethouseRepository repository.
        /// </summary>
        public static global::viethouse.viethouseRepository repo = global::viethouse.viethouseRepository.Instance;

        static QuanHuyenSai instance = new QuanHuyenSai();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public QuanHuyenSai()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static QuanHuyenSai Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ThongTinTaiKhoản2.XoaTấtCảCacMụcĐaChọn' at 10;18.", repo.ThongTinTaiKhoản2.XoaTấtCảCacMụcĐaChọnInfo, new RecordItemIndex(0));
            repo.ThongTinTaiKhoản2.XoaTấtCảCacMụcĐaChọn.Click("10;18");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ThongTinTaiKhoản2.Search' at 80;24.", repo.ThongTinTaiKhoản2.SearchInfo, new RecordItemIndex(1));
            repo.ThongTinTaiKhoản2.Search.Click("80;24");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Down}{Return}' with focus on 'ThongTinTaiKhoản2.Search'.", repo.ThongTinTaiKhoản2.SearchInfo, new RecordItemIndex(2));
            repo.ThongTinTaiKhoản2.Search.PressKeys("{Down}{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ThongTinTaiKhoản2.Select2DistrictIdContainer' at 181;10.", repo.ThongTinTaiKhoản2.Select2DistrictIdContainerInfo, new RecordItemIndex(3));
            repo.ThongTinTaiKhoản2.Select2DistrictIdContainer.Click("181;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ThongTinTaiKhoản2.Search' at 78;13.", repo.ThongTinTaiKhoản2.SearchInfo, new RecordItemIndex(4));
            repo.ThongTinTaiKhoản2.Search.Click("78;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'abc' with focus on 'ThongTinTaiKhoản2.Search'.", repo.ThongTinTaiKhoản2.SearchInfo, new RecordItemIndex(5));
            repo.ThongTinTaiKhoản2.Search.PressKeys("abc");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ThongTinTaiKhoản2.KhongTimThấyKếtQuả1'.", repo.ThongTinTaiKhoản2.KhongTimThấyKếtQuả1Info, new RecordItemIndex(6));
            Validate.Exists(repo.ThongTinTaiKhoản2.KhongTimThấyKếtQuả1Info);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
