///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace viethouse.MODULE.CapNhatThongTin.DiaChi
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The QuanHuyen recording.
    /// </summary>
    [TestModule("ee3626c0-f4f5-4b2e-b5d3-fac75eb5f77a", ModuleType.Recording, 1)]
    public partial class QuanHuyen : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::viethouse.viethouseRepository repository.
        /// </summary>
        public static global::viethouse.viethouseRepository repo = global::viethouse.viethouseRepository.Instance;

        static QuanHuyen instance = new QuanHuyen();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public QuanHuyen()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static QuanHuyen Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ThongTinTaiKhoản2.Select2ProvinceIdContainer' at 108;5.", repo.ThongTinTaiKhoản2.Select2ProvinceIdContainerInfo, new RecordItemIndex(0));
            repo.ThongTinTaiKhoản2.Select2ProvinceIdContainer.Click("108;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ThongTinTaiKhoản2.Search' at 121;10.", repo.ThongTinTaiKhoản2.SearchInfo, new RecordItemIndex(1));
            repo.ThongTinTaiKhoản2.Search.Click("121;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Down}{Return}' with focus on 'ThongTinTaiKhoản2.Search'.", repo.ThongTinTaiKhoản2.SearchInfo, new RecordItemIndex(2));
            repo.ThongTinTaiKhoản2.Search.PressKeys("{Down}{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ThongTinTaiKhoản2.Select2DistrictIdContainer' at 146;9.", repo.ThongTinTaiKhoản2.Select2DistrictIdContainerInfo, new RecordItemIndex(3));
            repo.ThongTinTaiKhoản2.Select2DistrictIdContainer.Click("146;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ThongTinTaiKhoản2.Search' at 121;23.", repo.ThongTinTaiKhoản2.SearchInfo, new RecordItemIndex(4));
            repo.ThongTinTaiKhoản2.Search.Click("121;23");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Quan Hoang Mai' with focus on 'ThongTinTaiKhoản2.Search'.", repo.ThongTinTaiKhoản2.SearchInfo, new RecordItemIndex(5));
            repo.ThongTinTaiKhoản2.Search.PressKeys("Quan Hoang Mai");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Down}{Return}' with focus on 'ThongTinTaiKhoản2.Search'.", repo.ThongTinTaiKhoản2.SearchInfo, new RecordItemIndex(6));
            repo.ThongTinTaiKhoản2.Search.PressKeys("{Down}{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ThongTinTaiKhoản2.ChangeInfo' at 169;32.", repo.ThongTinTaiKhoản2.ChangeInfoInfo, new RecordItemIndex(7));
            repo.ThongTinTaiKhoản2.ChangeInfo.Click("169;32");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ThongTinTaiKhoản2.CậpNhậtThongTinTaiKhoảnThanhCong1'.", repo.ThongTinTaiKhoản2.CậpNhậtThongTinTaiKhoảnThanhCong1Info, new RecordItemIndex(8));
            Validate.Exists(repo.ThongTinTaiKhoản2.CậpNhậtThongTinTaiKhoảnThanhCong1Info);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
