///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace viethouse.MODULE.CapNhatThongTin
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The HoTen19KyTu recording.
    /// </summary>
    [TestModule("1245edad-ed6d-4d7a-b90a-8abcb61dce5c", ModuleType.Recording, 1)]
    public partial class HoTen19KyTu : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::viethouse.viethouseRepository repository.
        /// </summary>
        public static global::viethouse.viethouseRepository repo = global::viethouse.viethouseRepository.Instance;

        static HoTen19KyTu instance = new HoTen19KyTu();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public HoTen19KyTu()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static HoTen19KyTu Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ThongTinTaiKhoản2.ProfileFullName' at 124;25.", repo.ThongTinTaiKhoản2.ProfileFullNameInfo, new RecordItemIndex(0));
            repo.ThongTinTaiKhoản2.ProfileFullName.Click("124;25");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'ThongTinTaiKhoản2.ProfileFullName'.", repo.ThongTinTaiKhoản2.ProfileFullNameInfo, new RecordItemIndex(1));
            Keyboard.PrepareFocus(repo.ThongTinTaiKhoản2.ProfileFullName);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}' with focus on 'ThongTinTaiKhoản2.ProfileFullName'.", repo.ThongTinTaiKhoản2.ProfileFullNameInfo, new RecordItemIndex(2));
            repo.ThongTinTaiKhoản2.ProfileFullName.PressKeys("{Back}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '' with focus on 'ThongTinTaiKhoản2.ProfileFullName'.", repo.ThongTinTaiKhoản2.ProfileFullNameInfo, new RecordItemIndex(3));
            repo.ThongTinTaiKhoản2.ProfileFullName.PressKeys("");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'T' with focus on 'ThongTinTaiKhoản2.ProfileFullName'.", repo.ThongTinTaiKhoản2.ProfileFullNameInfo, new RecordItemIndex(4));
            repo.ThongTinTaiKhoản2.ProfileFullName.PressKeys("T");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '' with focus on 'ThongTinTaiKhoản2.ProfileFullName'.", repo.ThongTinTaiKhoản2.ProfileFullNameInfo, new RecordItemIndex(5));
            repo.ThongTinTaiKhoản2.ProfileFullName.PressKeys("");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'ran' with focus on 'ThongTinTaiKhoản2.ProfileFullName'.", repo.ThongTinTaiKhoản2.ProfileFullNameInfo, new RecordItemIndex(6));
            repo.ThongTinTaiKhoản2.ProfileFullName.PressKeys("ran");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence ' Gia Luong Luon' with focus on 'ThongTinTaiKhoản2.ProfileFullName'.", repo.ThongTinTaiKhoản2.ProfileFullNameInfo, new RecordItemIndex(7));
            repo.ThongTinTaiKhoản2.ProfileFullName.PressKeys(" Gia Luong Luon");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ThongTinTaiKhoản2.ChangeInfo' at 129;26.", repo.ThongTinTaiKhoản2.ChangeInfoInfo, new RecordItemIndex(8));
            repo.ThongTinTaiKhoản2.ChangeInfo.Click("129;26");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ThongTinTaiKhoản2.CậpNhậtThongTinTaiKhoảnThanhCong'.", repo.ThongTinTaiKhoản2.CậpNhậtThongTinTaiKhoảnThanhCongInfo, new RecordItemIndex(9));
            Validate.Exists(repo.ThongTinTaiKhoản2.CậpNhậtThongTinTaiKhoảnThanhCongInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ThongTinTaiKhoảnGoogleChrome.TảiLại' at 20;12.", repo.ThongTinTaiKhoảnGoogleChrome.TảiLạiInfo, new RecordItemIndex(10));
            repo.ThongTinTaiKhoảnGoogleChrome.TảiLại.Click("20;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Value='Tran Gia Luong Luon') on item 'ThongTinTaiKhoản2.ProfileFullName'.", repo.ThongTinTaiKhoản2.ProfileFullNameInfo, new RecordItemIndex(11));
            Validate.AttributeEqual(repo.ThongTinTaiKhoản2.ProfileFullNameInfo, "Value", "Tran Gia Luong Luon");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
