///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace viethouse.MODULE.TimKiem
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The insert_search recording.
    /// </summary>
    [TestModule("1811eb31-c2f1-40d7-99bd-512ff8a6f5ea", ModuleType.Recording, 1)]
    public partial class insert_search : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::viethouse.viethouseRepository repository.
        /// </summary>
        public static global::viethouse.viethouseRepository repo = global::viethouse.viethouseRepository.Instance;

        static insert_search instance = new insert_search();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public insert_search()
        {
            edtSearch = "                               ";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static insert_search Instance
        {
            get { return instance; }
        }

#region Variables

        string _edtSearch;

        /// <summary>
        /// Gets or sets the value of variable edtSearch.
        /// </summary>
        [TestVariable("c6f0db6a-7d1c-4759-837c-727da26f72a5")]
        public string edtSearch
        {
            get { return _edtSearch; }
            set { _edtSearch = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TimKiem.TxtKeywords' at 406;24.", repo.TimKiem.TxtKeywordsInfo, new RecordItemIndex(0));
            repo.TimKiem.TxtKeywords.Click("406;24");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$edtSearch' with focus on 'TimKiem.TxtKeywords'.", repo.TimKiem.TxtKeywordsInfo, new RecordItemIndex(1));
            repo.TimKiem.TxtKeywords.PressKeys(edtSearch);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
