///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace viethouse.MODULE.TimKiem
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The validate_list recording.
    /// </summary>
    [TestModule("34eaa65b-b94c-40a5-82fc-4a224fc57480", ModuleType.Recording, 1)]
    public partial class validate_list : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::viethouse.viethouseRepository repository.
        /// </summary>
        public static global::viethouse.viethouseRepository repo = global::viethouse.viethouseRepository.Instance;

        static validate_list instance = new validate_list();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public validate_list()
        {
            validateList = "Đường 30/4, Thủ Dầu Một, Bình Dương";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static validate_list Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable validateList.
        /// </summary>
        [TestVariable("cb8c032d-34be-4178-8ad7-eeaddb9601c4")]
        public string validateList
        {
            get { return repo.validateList; }
            set { repo.validateList = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (InnerText>$validateList) on item 'TimKiem.validateListSearch.validateList1'.", repo.TimKiem.validateListSearch.validateList1Info, new RecordItemIndex(0));
            Validate.AttributeContains(repo.TimKiem.validateListSearch.validateList1Info, "InnerText", validateList);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (InnerText>$validateList) on item 'TimKiem.validateListSearch.validateList2'.", repo.TimKiem.validateListSearch.validateList2Info, new RecordItemIndex(1));
            Validate.AttributeContains(repo.TimKiem.validateListSearch.validateList2Info, "InnerText", validateList);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (InnerText>$validateList) on item 'TimKiem.validateListSearch.validateList3'.", repo.TimKiem.validateListSearch.validateList3Info, new RecordItemIndex(2));
            Validate.AttributeContains(repo.TimKiem.validateListSearch.validateList3Info, "InnerText", validateList);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (InnerText>$validateList) on item 'TimKiem.validateListSearch.validateList4'.", repo.TimKiem.validateListSearch.validateList4Info, new RecordItemIndex(3));
            Validate.AttributeContains(repo.TimKiem.validateListSearch.validateList4Info, "InnerText", validateList);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (InnerText>$validateList) on item 'TimKiem.validateListSearch.validateList5'.", repo.TimKiem.validateListSearch.validateList5Info, new RecordItemIndex(4));
            Validate.AttributeContains(repo.TimKiem.validateListSearch.validateList5Info, "InnerText", validateList);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
