///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace viethouse.MODULE.TimKiem
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The validate_type recording.
    /// </summary>
    [TestModule("ecb519f7-53ce-4e1c-9844-b4346665be21", ModuleType.Recording, 1)]
    public partial class validate_type : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::viethouse.viethouseRepository repository.
        /// </summary>
        public static global::viethouse.viethouseRepository repo = global::viethouse.viethouseRepository.Instance;

        static validate_type instance = new validate_type();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public validate_type()
        {
            validateType = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static validate_type Instance
        {
            get { return instance; }
        }

#region Variables

        string _validateType;

        /// <summary>
        /// Gets or sets the value of variable validateType.
        /// </summary>
        [TestVariable("ac17df41-a1bc-4f43-b7d3-d8710f226ffd")]
        public string validateType
        {
            get { return _validateType; }
            set { _validateType = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (InnerText>$validateType) on item 'TimKiem.validateType'.", repo.TimKiem.validateTypeInfo, new RecordItemIndex(0));
            Validate.AttributeContains(repo.TimKiem.validateTypeInfo, "InnerText", validateType);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
