///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace viethouse.MODULE.TimKiem
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The validate_search recording.
    /// </summary>
    [TestModule("c33e7972-ffdb-48f1-8284-4177e2cd4939", ModuleType.Recording, 1)]
    public partial class validate_search : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::viethouse.viethouseRepository repository.
        /// </summary>
        public static global::viethouse.viethouseRepository repo = global::viethouse.viethouseRepository.Instance;

        static validate_search instance = new validate_search();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public validate_search()
        {
            notification = "Mua bán nhà đất - Bất động sản House Viet T12/2021";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static validate_search Instance
        {
            get { return instance; }
        }

#region Variables

        string _notification;

        /// <summary>
        /// Gets or sets the value of variable notification.
        /// </summary>
        [TestVariable("e6f6e859-0d77-4703-9197-7d565f1c1659")]
        public string notification
        {
            get { return _notification; }
            set { _notification = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (InnerText>$notification) on item 'TimKiem.MuaBanNhaĐấtBấtĐộngSảnHouseVie'.", repo.TimKiem.MuaBanNhaĐấtBấtĐộngSảnHouseVieInfo, new RecordItemIndex(0));
            Validate.AttributeContains(repo.TimKiem.MuaBanNhaĐấtBấtĐộngSảnHouseVieInfo, "InnerText", notification);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
