///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace viethouse.MODULE.TimKiem
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The validate_search recording.
    /// </summary>
    [TestModule("6ec231b7-0c52-4f8f-8c23-f1eec65a1988", ModuleType.Recording, 1)]
    public partial class validate_search : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::viethouse.viethouseRepository repository.
        /// </summary>
        public static global::viethouse.viethouseRepository repo = global::viethouse.viethouseRepository.Instance;

        static validate_search instance = new validate_search();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public validate_search()
        {
            validateSearch = "Bạn đang xem 15 tin rao trong tổng số 21.211 tin .";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static validate_search Instance
        {
            get { return instance; }
        }

#region Variables

        string _validateSearch;

        /// <summary>
        /// Gets or sets the value of variable validateSearch.
        /// </summary>
        [TestVariable("8dd886d4-dae0-4888-99a0-ee62615b7f8e")]
        public string validateSearch
        {
            get { return _validateSearch; }
            set { _validateSearch = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (InnerText>$validateSearch) on item 'TimKiem.validateSearch'.", repo.TimKiem.validateSearchInfo, new RecordItemIndex(0));
            Validate.AttributeContains(repo.TimKiem.validateSearchInfo, "InnerText", validateSearch);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
