///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace viethouse.MODULE.TimKiem
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The validate_soil_type recording.
    /// </summary>
    [TestModule("d2c2b827-a9df-4f54-a683-e790016c721a", ModuleType.Recording, 1)]
    public partial class validate_soil_type : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::viethouse.viethouseRepository repository.
        /// </summary>
        public static global::viethouse.viethouseRepository repo = global::viethouse.viethouseRepository.Instance;

        static validate_soil_type instance = new validate_soil_type();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public validate_soil_type()
        {
            notification = "Mua bán nhà đất - Bất động sản House Viet T12/2021";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static validate_soil_type Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable element.
        /// </summary>
        [TestVariable("86bf0f96-bb1e-43e6-b947-1c34c4472a50")]
        public string element
        {
            get { return repo.element; }
            set { repo.element = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable notification.
        /// </summary>
        [TestVariable("bbad96b1-ce22-4841-bd34-735530116d87")]
        public string notification
        {
            get { return repo.notification; }
            set { repo.notification = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (InnerText>$notification) on item 'TimKiem.validateSoilType'.", repo.TimKiem.validateSoilTypeInfo, new RecordItemIndex(0));
            Validate.AttributeContains(repo.TimKiem.validateSoilTypeInfo, "InnerText", notification);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
